# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-Plugin-Ping
version:      0.45
version_from: lib/DJabberd/Plugin/Ping.pm
installdirs:  site
requires:
    DJabberd:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
